#include "hal_data.h"

/// @brief 标准库
#include <stdio.h>

/// @brief 应用层
#include "app/packet_parser.h"

/// @brief 设备层
#include "device/motor.h"
#include "device/wifi_bt.h"

/// @brief 领域层（机器人）
#include "domain/arm_kine.h"

/// @brief 基础设施层
#include "infra/delay.h"
#include "infra/fsm.h"
// #include "infra/matrix.h"
#include "infra/protocol_parser.h"

/// @brief 平台层
#include "platform/can.h"
#include "platform/led.h"
#include "platform/systick.h"
#include "platform/uart.h"

// 测试函数
void arm_test(WifiBtConnectInfo* info);

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/**
 * @brief 系统初始化函数
 * @note 该函数在 hal_entry() 中被调用，用于初始化系统资源和外设
 */
static void sys_init(RingBuf* uart7_rx_buf, WifiBtConnectInfo* info) {
    if(systick.init() != FSP_SUCCESS) while(1);
    delay_ms_init(systick.get_ms);

    uart.init(UART7, uart7_rx_buf);
    wifi.init(UART6, STA, (const uint8_t*)"RENE:", 5);
    can.init();

    dm.enable(0x01);
    dm.enable(0x02);
    dm.enable(0x03);
    dm.enable(0x04);
    dm.enable(0x05);
    dm.enable(0x06);

    delay_ms(2000);
    led.on();
    printf("System Init Complete!\r\n");

    if(wifi.join_ap(info->ssid, info->password) != wifi.OK) printf("WiFi 连接失败!\r\n");
    else printf("WiFi 连接成功!\r\n");

    float dx = 0.244004f;
    float dy = 0.059971f;
    float phi = atan2f(dy, dx);
    float a3 = sqrtf(powf(dx, 2) + powf(dy, 2));
    static ArmMDH mdh;
    mdh = (ArmMDH){
        .alpha = { 0, -M_PI / 2, M_PI, 0, M_PI / 2, M_PI / 2 },
        .a = { 0, 0.02f, 0.264f, a3, 0.061868f, 0 },
        .d = { 0.1f, 0, 0, 0, 0, 0.19f },
        .offset = { M_PI / 2, M_PI, phi - M_PI, -phi, M_PI / 2, 0 },
        .qmin = { -2.0944f, 0, 0, -M_PI / 2, -M_PI / 2, -M_PI },
        .qmax = { 2.0944f, M_PI, 1.5f * M_PI, M_PI / 2, M_PI / 2, M_PI }
    };
    arm.init(&mdh);

    fsm_init(info);
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {
    /* TODO: add your own code here */

    static uint8_t uart6_buffer[256];
    static RingBuf buf6;
    RingBufCreate(&buf6, uart6_buffer, sizeof(uart6_buffer), 1);

    static uint8_t uart7_buffer[256];
    static RingBuf buf7;
    RingBufCreate(&buf7, uart7_buffer, sizeof(uart7_buffer), 1);

    static WifiBtConnectInfo info = {
        .ssid = "K230",
        .password = "12345678",
        .protocol = UDP,
        .role = Client,
        .ip = "192.168.169.1",
        .remote_port = 8080,
        .local_port = 5000
    };
    sys_init(&buf7, &info);

    static ms_t dm_update_task = 0;
    static ms_t printf_task = 0;

    static DmMotorFeedback feedback;
    static uint16_t feedback_fps = 0;

    static WeedData weed_data;
    static uint8_t* frame_buf = NULL;
    static uint16_t frame_len = 0;

    static WifiBtStatus net_status;

    while(1) {
        fsm_process();

        net_status = wifi.heartbeat(&info, 2000);
        if(net_status == wifi.OK) {
            if(wifi.process(&frame_buf, &frame_len) == wifi.FRAME_READY) {
                comms.process(frame_buf, frame_len);
                comms.get_weed(&weed_data);
                if(weed_data.confidence > 0.8) {
                    if(!fsm_trigger(EVENT_START_SEARCH, &weed_data)) {
                        printf("[FSM] 无法触发事件：%d\r\n", EVENT_START_SEARCH);
                    }
                }
                if(frame_len == 8 && memcmp((const char*)frame_buf, "Laser OK", 8) == 0) {
                    if(!fsm_trigger(EVENT_LASER_COMPLETE, NULL)) {
                        printf("[FSM] 无法触发事件：%d\r\n", EVENT_LASER_COMPLETE);
                    }
                }
            }
        }

        while(dm.update(&feedback) == dm.OK) {
            fsm_update_dm_feedback(feedback);
            ++feedback_fps;
        }
        if(s_nb_delay_ms(&dm_update_task, 20)) {
            dm.request_feedback(0x01);
            dm.request_feedback(0x02);
            dm.request_feedback(0x03);
            dm.request_feedback(0x04);
            dm.request_feedback(0x05);
            dm.request_feedback(0x06);
        }

        if(s_nb_delay_ms(&printf_task, 2000)) {
            printf("Net Status: %d, DM FPS: %d, WEED: %u, %.2f, %.2f, %.2f, %.2f\r\n", net_status, feedback_fps, weed_data.id, weed_data.x, weed_data.y, weed_data.z, weed_data.confidence);

            feedback_fps = 0;
        }
    }



    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore)) {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable() {

}
FSP_CPP_FOOTER

#endif

void arm_test(WifiBtConnectInfo* info) {
    SixDofJoint joints = { 0.0f, 0.0f, 0.01f, 0.0f, 0.0f, 0.0f };
    Pose pose;
    arm.fk(&joints, &pose);
    pose.position.x = 0.1f;
    pose.position.y = 0.3f;
    pose.position.z = 0.2f;

    SixDofJoint ik_joints = { 0 };
    ArmStatus ret = arm.ik(&pose, &ik_joints, &joints, IK_MODE_POSITION_ONLY);
    if(ret != ARM_STATUS_SUCCESS) {
        printf("IK failed: %d\r\n", ret);
        return;
    }

    printf("IK Joints: %f, %f, %f, %f, %f, %f\r\n", ik_joints.joint_1, ik_joints.joint_2, ik_joints.joint_3, ik_joints.joint_4, ik_joints.joint_5, ik_joints.joint_6);
    char joint_buf[128];
    int len = snprintf(joint_buf, sizeof(joint_buf), "IK Joints: %f %f %f %f %f %f", ik_joints.joint_1, ik_joints.joint_2, ik_joints.joint_3, ik_joints.joint_4, ik_joints.joint_5, ik_joints.joint_6);
    wifi.send(*info, joint_buf, (uint16_t)len);

    Pose verify_pose;
    arm.fk(&ik_joints, &verify_pose);
    printf("Position error: %f %f %f\r\n", pose.position.x - verify_pose.position.x, pose.position.y - verify_pose.position.y, pose.position.z - verify_pose.position.z);
    len = snprintf(joint_buf, sizeof(joint_buf), "Position error: %f %f %f", pose.position.x - verify_pose.position.x, pose.position.y - verify_pose.position.y, pose.position.z - verify_pose.position.z);
    wifi.send(*info, joint_buf, (uint16_t)len);

    dm.set_pos_spd(0x01, ik_joints.joint_1, 1.57f);
    dm.set_pos_spd(0x02, ik_joints.joint_2, 1.57f);
    dm.set_pos_spd(0x03, ik_joints.joint_3, 1.57f);
    dm.set_pos_spd(0x04, ik_joints.joint_4, 1.57f);
    dm.set_pos_spd(0x05, ik_joints.joint_5, 1.57f);
    dm.set_pos_spd(0x06, ik_joints.joint_6, 1.57f);

    printf("Starting IK tests...\r\n");
    SixDofJointAll all_joints = { 0 };
    ret = arm.all_ik(&pose, &all_joints, IK_MODE_POSITION_ONLY);
    if(ret != ARM_STATUS_SUCCESS) {
        printf("All IK failed: %d\r\n", ret);
        return;
    }
    printf("Found %d IK solutions\r\n", all_joints.num_solutions);
    for(uint8_t i = 0; i < all_joints.num_solutions; i++) {
        SixDofJoint* s = arm.solution_select(&all_joints, i);
        if(!s) continue;
        printf("--------------------------------------------------\r\n");
        printf("- Solution: %d, %f, %f, %f, %f, %f, %f\r\n", i + 1, s->joint_1, s->joint_2, s->joint_3, s->joint_4, s->joint_5, s->joint_6);

        arm.fk(s, &verify_pose);
        printf("- Position Error: %f, %f, %f\r\n", verify_pose.position.x - pose.position.x, verify_pose.position.y - pose.position.y, verify_pose.position.z - pose.position.z);
        printf("--------------------------------------------------\r\n");
    }
}
