#include "drive/d_dm_motor.h"
#include "hal_data.h"

// 工具库
// #include "tools/simple_api.h"
#include "tools/ring_buf.h"

// 标准库
#include <stdint.h>
#include <stdio.h>

// 驱动层
#include "drive/d_led.h"
#include "drive/d_uart.h"
#include "drive/d_can.h"
#include "drive/d_systick.h"

// 服务层
#include "service/s_delay.h"

// 应用层

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/**
 * @brief 系统初始化函数
 * @note 该函数在 hal_entry() 中被调用，用于初始化系统资源和外设
 */
void sys_init(RingBuf_t* uart_rx_buf);
void sys_init(RingBuf_t* uart_rx_buf) {
    // 初始化 SysTick 定时器
    if(d_systick_init() != FSP_SUCCESS) {
        while(1);
    }
    s_delay_init(d_systick_get_ms, d_systick_is_timeout);

    d_uart_init(UART7, uart_rx_buf);
    d_can_init();

    s_delay_ms(2000);
    d_led_on();
    printf("System Init Complete!\r\n");

    d_dm_enable(0x01);
    printf("Enable DM 1!\r\n");
    d_dm_set_spd(0x01, 3.14f);
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {
    /* TODO: add your own code here */

    int rx_data;

    uint8_t rx_buffer[256];
    RingBuf_t buf;
    RingBuf(&buf, rx_buffer, sizeof(rx_buffer), 1);

    sys_init(&buf);

    uint16_t count = 0;

    while(1) {
        if(buf.read(&buf, (uint8_t*)&rx_data) == RING_BUF_OK) {
            printf("read: %c\r\n", rx_data);
        }
        printf("now: %u\r\n", count);
        count++;
        s_delay_s(1);
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore)) {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable() {

}
FSP_CPP_FOOTER

#endif
