#include "drive/d_dm_motor.h"
#include "hal_data.h"

// 工具库
#include "tools/simple_api.h"
#include "tools/ring_buf.h"

// 标准库
#include <stdint.h>
#include <stdio.h>
#include <sys/_types.h>

// 驱动层
#include "drive/d_led.h"
#include "drive/d_uart.h"
#include "drive/d_can.h"
#include "drive/d_systick.h"
#include "drive/d_wifi_bt.h"

// 服务层
#include "service/s_delay.h"
#include "service/s_fk_ik.h"
// #include "service/s_comms.h"

// 应用层



// 测试函数
void fk_ik_test();

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/**
 * @brief 系统初始化函数
 * @note 该函数在 hal_entry() 中被调用，用于初始化系统资源和外设
 */
void sys_init(RingBuf* uart7_rx_buf, WifiBtConnectInfo* info);
void sys_init(RingBuf* uart7_rx_buf, WifiBtConnectInfo* info) {
    if(d_systick_init() != FSP_SUCCESS) while(1);
    s_delay_init(d_systick_get_ms, d_systick_is_timeout);

    d_uart_init(UART7, uart7_rx_buf);
    d_wifi_bt_init(UART6, STA, (const uint8_t*)"WEED:", 5);
    d_can_init();

    s_delay_ms(2000);
    d_led_on();
    printf("System Init Complete!\r\n");

    info->ssid = "K230";
    info->password = "12345678";
    info->protocol = TCP;
    info->role = Client;
    strcpy(info->ip, "192.168.169.1");
    info->remote_port = 8080;
    info->local_port = 5000;
    d_wifi_bt_join_ap(info->ssid, info->password);

    // fk_ik_test();
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {
    /* TODO: add your own code here */

    uint8_t uart6_buffer[256];
    RingBuf buf6;
    RingBufCreate(&buf6, uart6_buffer, sizeof(uart6_buffer), 1);

    uint8_t uart7_buffer[256];
    RingBuf buf7;
    RingBufCreate(&buf7, uart7_buffer, sizeof(uart7_buffer), 1);

    WifiBtConnectInfo info;
    sys_init(&buf7, &info);

    ms_t dm_update_task = 0;
    ms_t connect_retry_task = 0;
    ms_t send_task = 0;

    DmMotorFeedback_t feedback;

    uint32_t send_count = 0;
    bool is_connected = false;
    uint8_t retry_count = 0;

    while(1) {
        if(s_nb_delay_ms(&dm_update_task, 10)) {
            d_dm_request_feedback(0x01);
            d_dm_update(&feedback);
        }
        if(!is_connected) {
            if(s_nb_delay_ms(&connect_retry_task, 1000)) {
                if(d_wifi_bt_check_ap() != WIFI_BT_SUCCESS) {
                    printf("WiFi 未连接，尝试重连...\r\n");
                    if(d_wifi_bt_rejoin_ap(NULL, NULL) != WIFI_BT_SUCCESS)
                        printf("WiFi 重连失败，继续等待...\r\n");
                    continue;
                }

                printf("尝试 TCP 连接... (retry=%d)\r\n", retry_count);
                if(d_wifi_bt_connect(&info, 1000) == WIFI_BT_SUCCESS) {
                    is_connected = true;
                    send_count = 0;
                    retry_count = 0;
                    printf("连接成功!\r\n");
                }

                else if(++retry_count < 3) printf("连接失败，1 秒后重试\r\n");
                else {
                    printf("连接失败,重试次数过多,正在重置 WiFi 模块...\r\n");
                    retry_count = 0;
                    if(d_wifi_bt_reset(STA) == WIFI_BT_SUCCESS) d_wifi_bt_join_ap(info.ssid, info.password);
                    else printf("模块重置失败\r\n");
                }
            }
            continue;
        }
        if(s_nb_delay_ms(&send_task, 1000)) {
            // 手动封装帧：帧头(5) + 长度(2) + 载荷(10) = 17 字节
            uint8_t frame[5 + 2 + 10] = { 0 };
            uint8_t payload[10] = { 0 };
            snprintf((char*)payload, sizeof(payload), "PING %04lu", (unsigned long)send_count);

            memcpy(frame, "WEED:", 5);
            frame[5] = 0x00;
            frame[6] = 10;
            memcpy(frame + 7, payload, 10);

            if(d_wifi_bt_send_frame(info, frame, sizeof(frame)) == WIFI_BT_SUCCESS) {
                printf("发送 [%lu]: %s\r\n", (unsigned long)send_count, (char*)payload);
                send_count++;
            }
            else {
                printf("发送失败，触发重连\r\n");
                d_wifi_bt_disconnect(info);
                is_connected = false;
            }
        }

        uint8_t* frame_buf = NULL;
        uint16_t frame_len = 0;

        if(d_wifi_bt_process(&frame_buf, &frame_len) == WIFI_BT_FRAME_READY) {
            char print_buf[WIFI_BT_FRAME_BUF_SIZE + 1];
            uint16_t copy_len = (frame_len < WIFI_BT_FRAME_BUF_SIZE) ? frame_len : WIFI_BT_FRAME_BUF_SIZE;
            memcpy(print_buf, frame_buf, copy_len);
            print_buf[copy_len] = '\0';
            printf("收到: %s\r\n", print_buf);
            d_wifi_bt_finish_frame();
        }
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore)) {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable() {

}
FSP_CPP_FOOTER

#endif

void fk_ik_test() {
    // 测试电机
    d_dm_enable(0x01);
    d_dm_enable(0x02);
    d_dm_enable(0x03);
    d_dm_enable(0x04);
    d_dm_enable(0x05);
    d_dm_enable(0x06);

    // 测试 FK - IK
    s_delay_ms(1000);
    float dx = 0.244004f;
    float dy = 0.059971f;
    float phi = atan2f(dy, dx);
    float a3 = sqrtf(powf(dx, 2) + powf(dy, 2));
    ArmMDH mdh = {
        .alpha = { 0, -M_PI / 2, M_PI, 0, M_PI / 2, M_PI / 2 },
        .a = { 0, 0.02f, 0.264f, a3, 0.061868f, 0 },
        .d = { 0.1f, 0, 0, 0, 0, 0.19f },
        .offset = { M_PI / 2, M_PI, phi - M_PI, -phi, M_PI / 2, 0 },
        .qmin = { -2.0944f, 0, 0, -M_PI / 2, -M_PI / 2, -M_PI },
        .qmax = { 2.0944f, M_PI, 1.5f * M_PI, M_PI / 2, M_PI / 2, M_PI }
    };
    s_six_dof_init(&mdh);

    SixDofJoint joints = { 0.0f, 0.0f, 0.01f, 0.0f, 0.0f, 0.0f };
    Pose pose;
    s_six_dof_fk(&joints, &pose);
    pose.position.x = 0.1f;
    pose.position.y = 0.3f;
    pose.position.z = 0.2f;

    SixDofJoint ik_joints = { 0 };
    ArmErrorCode ret = s_six_dof_ik(&pose, &ik_joints, &joints, IK_MODE_POSITION_ONLY);
    if(ret != ARM_SUCCESS) {
        printf("IK failed: %d\r\n", ret);
        return;
    }

    printf("IK Joints: ");
    printf_float(ik_joints.joint_1); printf(" ");
    printf_float(ik_joints.joint_2); printf(" ");
    printf_float(ik_joints.joint_3); printf(" ");
    printf_float(ik_joints.joint_4); printf(" ");
    printf_float(ik_joints.joint_5); printf(" ");
    printf_float(ik_joints.joint_6); printf("\r\n");

    Pose verify_pose;
    s_six_dof_fk(&ik_joints, &verify_pose);
    printf("Position error: ");
    printf_float(pose.position.x - verify_pose.position.x); printf(" ");
    printf_float(pose.position.y - verify_pose.position.y); printf(" ");
    printf_float(pose.position.z - verify_pose.position.z); printf("\r\n");

    d_dm_set_pos_spd(0x01, ik_joints.joint_1, 1.57f);
    d_dm_set_pos_spd(0x02, ik_joints.joint_2, 1.57f);
    d_dm_set_pos_spd(0x03, ik_joints.joint_3, 1.57f);
    d_dm_set_pos_spd(0x04, ik_joints.joint_4, 1.57f);
    d_dm_set_pos_spd(0x05, ik_joints.joint_5, 1.57f);
    d_dm_set_pos_spd(0x06, ik_joints.joint_6, 1.57f);

    // printf("Starting IK tests...\r\n");
    // SixDofJointAll all_joints = { 0 };
    // ArmErrorCode ret = s_six_dof_all_ik(&pose, &all_joints, IK_MODE_POSITION_ONLY);
    // if(ret != ARM_SUCCESS) {
    //     printf("All IK failed: %d\r\n", ret);
    //     return;
    // }
    // printf("Found %d IK solutions\r\n", all_joints.num_solutions);
    // for(uint8_t i = 0; i < all_joints.num_solutions; i++) {
    //     SixDofJoint* s = solution_select(&all_joints, i);
    //     if(!s) continue;
    //     printf("--------------------------------------------------\r\n");
    //     printf("- Solution %d: ", i + 1);
    //     printf_float(s->joint_1); printf(" ");
    //     printf_float(s->joint_2); printf(" ");
    //     printf_float(s->joint_3); printf(" ");
    //     printf_float(s->joint_4); printf(" ");
    //     printf_float(s->joint_5); printf(" ");
    //     printf_float(s->joint_6); printf("\r\n");

    //     Pose verify_pose;
    //     s_six_dof_fk(s, &verify_pose);
    //     printf("- Position Error: ");
    //     printf_float(verify_pose.position.x - pose.position.x); printf(" ");
    //     printf_float(verify_pose.position.y - pose.position.y); printf(" ");
    //     printf_float(verify_pose.position.z - pose.position.z); printf("\r\n");
    //     printf("--------------------------------------------------\r\n");
    // }
}
